import java.util.Random;
import java.util.Scanner;

public class NumberGuessing {

    public static void guessthenumber() {
        Scanner sc = new Scanner(System.in);
        int max = 100;
        Random ran = new Random();
        System.out.println("Random number generated by computer");
        int n = ran.nextInt(max);    //it is the limit of the random number
        int count = 0;
        for (int i = 0; i < 100; i++) {
            System.out.println("Guess the number between 1 - 100 : ");                      //For loop to check conditions
            int a = sc.nextInt();
            if (a == n) {
                System.out.println("This is the Number ! you guessed, right Great : " + a+"\nand the count taken are :  "+count);
                break;
            } else if (a > n) {
                System.out.print("Guessed number is greater than the random number, try again ");
                count++;
            } else {
                System.out.print("Guessing number is less than the random number, try again : ");
                count++;
            }
        }

    }

    public static void main(String[] args) {

        guessthenumber();                                           //function calling
    }
}
